version: "3.4"
services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  loader:
    container_name: ${LOADER_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TARGET=${LOADER_SERVICE_NAME}
    depends_on:
      postgres:
        condition: service_healthy

  api:
    container_name: ${API_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TARGET=${API_SERVICE_NAME}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
      - loader

volumes:
  postgres_data:
